#!/bin/bash

echo "DB_URL=${{secrets.DB_URL}}"
echo "DB_USER=${{secrets.DB_USER}}"
echo "DB_PW=${{secrets.DB_PW}}"
echo "LOG_FILE_PATH=${{secrets.LOG_FILE_PATH}}"
echo "GITHUB_CLIENT_ID=${{secrets._GITHUB_CLIENT_ID}}"
echo "GITHUB_CLIENT_SECRET=${{secrets._GITHUB_CLIENT_SECRET}}"
echo "GITHUB_REDIRECT_URL=${{secrets._GITHUB_REDIRECT_URL}}"
echo "GITHUB_TOKEN_URL=${{secrets._GITHUB_TOKEN_URL}}"
echo "GITHUB_USER_INFO_URL=${{secrets._GITHUB_USER_INFO_URL}}"
echo "JWT_SECRET=${{secrets.JWT_SECRET}}"
echo "JWT_ACCESS_TOKEN_EXPIRE_TIME=${{secrets.JWT_ACCESS_TOKEN_EXPIRE_TIME}}"
echo "JWT_REFRESH_TOKEN_EXPIRE_TIME=${{secrets.JWT_REFRESH_TOKEN_EXPIRE_TIME}}"
echo "AWS_KEY_ID=${{secrets.AWS_KEY_ID}}"
echo "AWS_KEY_SECRET=${{secrets.AWS_KEY_SECRET}}"
echo "AWS_REGION_NAME=${{secrets.AWS_REGION_NAME}}"
echo "AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}}"
